### ISSUE TITLE
CAMELYON16 Patches

### ISSUE THREAD

**Issue by jmayank23** [tand826/WSIPatcher#2]
I am working with .tif files from the CAMELYON16 Dataset and that does not provide any rule files, can I still use this tool to generate hundreds/thousands of patches from each tif file?

**Comment by tand826** [comment]
@jmayank23 
Thank you the question, and I'm sorry for my late reply.
"Rule file" is a file that [wsiprocess](https://github.com/tand826/wsiprocess) uniquely uses for defining the classes to extract. You need to create a rule file to define which classes to extract like below.

```rule.json
{
  "metastases": {
    "includes": [],
    "excludes": []
  }
}
```

I recommend you to use wsiprocess from command line, because actually I used wsiprocess to extract patches from CAMELYON17 for my research, with some additional parameters which WSIPatcher cannot handle.

For example, the command below will give you patches from `patient_004_node_0.tif`, and these patches are 100% on the foreground area calculated with Otsu's thresholding. In this case, you don't need rule files.
`wsiprocess none center_0/patient_004_node_0.tif -of 1.0`

**Comment by tand826** [comment]
@jmayank23 
I close this issue because there is no active conversation. Feel free to reopen this issue if you have any questions.
